### ISSUE TITLE
8.2.0+ breaks sneaking with Left Shift

### ISSUE THREAD

**Issue by ghost** [blay09/InventoryEssentials#19]
### Minecraft Version

1.20.x

### Mod Loader

Quilt/Fabric

### Mod Loader Version

Tested on:
* Quilt Loader 0.20.2, Quilted Fabric API 7.2.2+0.88.1-1.20.1
* Fabric Loader 0.14.22, Fabric API 0.88.1+1.20.1

### Mod Version

8.2.0/8.2.1

### Balm Version

7.1.1

### Describe the Issue

Inventory Essentials 8.2.0/8.2.1 breaks sneaking if it's bound to Left Shift. If I rebind it to something else, it works.

Reproduced on a clean profile with just Balm, Inventory Essentials and Quilted Fabric API installed.

The only time it doesn't happen is if you install it on a brand new profile where options.txt doesn't exist yet. Then it works until you quit and restart Minecraft.

### Logs

https://mclo.gs/Tx0Mofq

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium etc. but happens without them

**Comment by 0xallie** [comment]
OK, it may be more complicated than that. It weirdly didn't happen on my test profile until I copied over the config, but now even completely wiping the config didn't fix it.

**Comment by AqueleHaru** [comment]
Just an update: i cant click with left button too. doesnt work.

**Comment by Edrow-6** [comment]
Just an update: 8.1.0 is broken too.

**Comment by BlayTheNinth** [comment]
Should be fixed in Balm 7.1.3

**Comment by Edrow-6** [comment]
Hi, but dont close the issue, because it's isn't fixed. Versions after 8.0.0 doesn't work. And the new version 8.2.1 have the same problem.

If it can help, i use Controlling for Fabric v12.0.2 in my pack.

**Comment by BlayTheNinth** [comment]
What Balm version are you using?

**Comment by Edrow-6** [comment]
> What Balm version are you using?

Balm version 7.1.3

**Comment by AqueleHaru** [comment]
same here

**Comment by BlayTheNinth** [comment]
Couldn't reproduce running 

- Balm 7.1.3 / 7.1.4
- Inventory Essentials 8.2.1
- Controlling 12.0.2
- Fabric API 0.83.0

However, I did find the issue happening in Crafting Tweaks as well, which has now been fixed in Balm 7.1.4. Did you maybe have Crafting Tweaks installed as well?

Do the keys show as conflicting in the Controls menu?

Please upload logs if it's still happening to you even after upgrading to Balm 7.1.4.

**Comment by Edrow-6** [comment]
I was using Crafting Tweaks too, removed now, no key conflicts and no Balm-related errors as far as I can see.
_Shift, CTRL, Left Click and maybe other keys doesn't work._

Here are my logs (sorry for any unnecessary errors)
https://mclo.gs/w4kHWyA

Edit: No issue using Balm 7.1.4 and InventoryEssentials 8.0.0.
        The issue is comming from IE for sure.
        
Maybe it comes from here? The problem starts in 8.1.0.
https://github.com/TwelveIterationMods/InventoryEssentials/commit/22c0a3513c6b4cea20fec03c0e2ad13c6f9f8915

**Comment by BlayTheNinth** [comment]
Can you try triggering a crash by holding F3 and C? A crash log may hold some more information.

**Comment by Edrow-6** [comment]
> Can you try triggering a crash by holding F3 and C? A crash log may hold some more information.

Crash log: https://mclo.gs/7phMqiy

**Comment by ghost** [comment]
For me it's fine now, no Crafting Tweaks, Balm 7.1.4, Inventory Essentials 8.2.1.

**Comment by wilebaldo** [comment]
I have the same problem, when I sneeking (shift) and try to use the left Click to destroy any block is not working, his is happening with the version of inventory essentials 8.2 but as soon I go back to the version 8.1 everything is working perfectly.

I have installed Balm 7.2.1 and fabric and minecraft 1.20.1

**Comment by wilebaldo** [comment]
It is me again, the mod was working ok on Minecraft 1.20.1 now in 1.20.4 is happen the same problem than before I already go to the older version I can with Minecraft 1.20.4 that is 9.0.1 and the older version for inventory essentials 10.0.1 but not working.

I see this mods alwas has problem to update so I think I don't will use anymore.
